GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "NewUser123",
  "name": "Pedro Perez",
  "password": "12345678"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "FirstUser",  
  "password": "12345678"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer 

{
  "title": "Blog6",
  "author": "person2",
  "url": "http://Blog6.com",
  "likes": 8
}

###
DELETE http://localhost:3003/api/blogs/667ad13816647555be02529d
Authorization: Bearer 
