GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "NewUser123",
  "name": "Pedro Perez",
  "password": "12345678"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "FirstUser",  
  "password": "12345678"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZpcnN0VXNlciIsImlkIjoiNjY2OWY0Y2I4NzVmMDIwZTc3ZDc2NzkyIiwiaWF0IjoxNzE5MzIwOTc4fQ.PkCNASbvDMudKbpa4L5Da6ZSUZI6TiLmO4GWltgDyFw

{
  "title": "Blog6",
  "author": "person2",
  "url": "http://Blog6.com",
  "likes": 8
}

###
DELETE http://localhost:3003/api/blogs/667ad13816647555be02529d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZpcnN0VXNlciIsImlkIjoiNjY2OWY0Y2I4NzVmMDIwZTc3ZDc2NzkyIiwiaWF0IjoxNzE5MzIwOTc4fQ.PkCNASbvDMudKbpa4L5Da6ZSUZI6TiLmO4GWltgDyFw