GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "NewBlog",
  "author": "Sabrina",
  "url": "http://New_Blog.com",
  "likes": 3,
  "userId": "6669f4cb875f020e77d76792"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "NewUser123",
  "name": "Pedro Perez",
  "password": "12345678"
}
